# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-02 10:59
from __future__ import unicode_literals

import Homes.Houses.utils
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserBase', '0054_auto_20180708_1743'),
        ('Owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, choices=[('inhouse', 'In-House'), ('society', 'Society')], max_length=25, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Homes.Houses.utils.get_amenity_picture_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.CharField(blank=True, max_length=10, null=True)),
                ('availability', models.CharField(choices=[('sold_out', 'Sold out'), ('not_available', 'Not available'), ('available', 'Available')], default='available', max_length=20)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('cover_pic_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('house_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('independent', 'Independent'), ('villa', 'Villa')], max_length=25, null=True)),
                ('furnish_type', models.CharField(blank=True, choices=[('full', 'Fully furnished'), ('semi', 'Semi furnished'), ('nil', 'Unfurnished')], max_length=25, null=True)),
                ('available_accomodation_types', multiselectfield.db.fields.MultiSelectField(choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=25)),
                ('accomodation_allowed', multiselectfield.db.fields.MultiSelectField(choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family')], max_length=25)),
                ('house_size', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='Owners.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='HouseAddressDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Houses.House')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseAmenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_amenities', to='Houses.Amenity')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='Houses.House')),
            ],
            options={
                'verbose_name_plural': 'House Amenities',
            },
        ),
        migrations.CreateModel(
            name='HousePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Homes.Houses.utils.get_house_picture_upload_path)),
                ('is_cover_pic', models.BooleanField(default=False)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='Houses.House')),
            ],
        ),
        migrations.CreateModel(
            name='HouseVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('scheduled_visit_time', models.DateTimeField(blank=True, null=True)),
                ('visited', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('actual_visit_time', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_visits', to='UserBase.Customer')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='Houses.House')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Monthly expense categories',
            },
        ),
        migrations.CreateModel(
            name='PrivateRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SharedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=20)),
                ('rent', models.FloatField()),
                ('security_deposit', models.FloatField()),
                ('availability', models.CharField(choices=[('sold_out', 'Sold out'), ('not_available', 'Not available'), ('available', 'Available')], default='available', max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='Houses.House')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceMonthlyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_monthly_expenses', to='Houses.MonthlyExpenseCategory')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_expenses', to='Houses.Space')),
            ],
        ),
        migrations.CreateModel(
            name='SubAmenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Homes.Houses.utils.get_sub_amenity_picture_upload_path)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_amenities', to='Houses.Amenity')),
            ],
            options={
                'verbose_name_plural': 'Sub Amenities',
            },
        ),
        migrations.AddField(
            model_name='sharedroom',
            name='space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shared_room', to='Houses.Space'),
        ),
        migrations.AddField(
            model_name='privateroom',
            name='space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_room', to='Houses.Space'),
        ),
        migrations.AddField(
            model_name='houseamenity',
            name='sub_amenities',
            field=models.ManyToManyField(blank=True, related_name='house_sub_amenities', to='Houses.SubAmenity'),
        ),
        migrations.AddField(
            model_name='flat',
            name='space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flat', to='Houses.Space'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='Houses.SharedRoom'),
        ),
    ]
