# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bhk_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
