# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-05 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0002_ownerpayment_category'),
        ('Houses', '0003_auto_20180804_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, choices=[('Plan A', 'Plan A')], max_length=100, null=True)),
                ('house_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('independent', 'Independent'), ('villa', 'Villa')], max_length=25, null=True)),
                ('furnish_type', models.CharField(blank=True, choices=[('full', 'Fully furnished'), ('semi', 'Semi furnished'), ('nil', 'Unfurnished')], max_length=25, null=True)),
                ('accomodation_allowed', multiselectfield.db.fields.MultiSelectField(choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family')], max_length=25)),
                ('current_status', models.CharField(blank=True, choices=[("I'm staying", "I'm staying"), ('Tenant is staying', 'Tenant is staying'), ("It's vacant", "It's vacannt")], max_length=50, null=True)),
                ('bhk_count', models.PositiveIntegerField(default=1)),
                ('current_rent', models.FloatField()),
                ('current_security_deposit', models.FloatField()),
                ('expected_rent', models.FloatField()),
                ('expected_security_deposit', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='Owners.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='HouseApplicationAddressDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Houses.HouseApplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='space',
            name='commission',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to='Houses.HouseApplication'),
        ),
    ]
