# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-05 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0005_auto_20180805_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseapplication',
            old_name='current_status',
            new_name='current_stay_status',
        ),
        migrations.AddField(
            model_name='houseapplication',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Complete', 'Complete')], default='New', max_length=20),
        ),
    ]
