# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0006_auto_20180805_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='houseapplication',
            name='accomodation_allowed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family')], default=False, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseapplication',
            name='plan',
            field=models.CharField(blank=True, choices=[('Plan A', 'Plan A'), ('Plan B', 'Plan B'), ('Plan C', 'Plan C')], max_length=100, null=True),
        ),
    ]
