# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0008_auto_20180806_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='bhk_count',
        ),
    ]
