# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0010_housevisit_area_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='preferred_food',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
