# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0011_house_preferred_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housevisit',
            options={'ordering': ('scheduled_visit_time',)},
        ),
        migrations.AlterField(
            model_name='bed',
            name='availability',
            field=models.CharField(choices=[('Sold Out', 'Sold Out'), ('Not Available', 'Not Available'), ('available', 'Available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='Houses.SharedRoom'),
        ),
        migrations.AlterField(
            model_name='houseapplication',
            name='current_stay_status',
            field=models.CharField(blank=True, choices=[("I'm staying", "I'm staying"), ('Tenant is staying', 'Tenant is staying'), ("It's vacant", "It's vacant")], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='availability',
            field=models.CharField(choices=[('Sold Out', 'Sold Out'), ('Not Available', 'Not Available'), ('available', 'Available')], default='available', max_length=20),
        ),
    ]
