# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0012_auto_20181005_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='agreement_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
