# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-04 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0014_housefurnishingbill_housefurnishingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bedroom', 'Bedroom'), ('Living Room', 'Living Room'), ('Kitchen & Dining Hall', 'Kitchen & Dining Hall'), ('Bathroom', 'Bathroom'), ('Others', 'Others')], max_length=25)),
                ('name', models.CharField(max_length=150)),
                ('count', models.IntegerField(default=1)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_facilities', to='Houses.House')),
            ],
        ),
    ]
