# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-04 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0015_existingfacility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='existingfacility',
            options={'verbose_name_plural': 'Existing facilities'},
        ),
        migrations.AddField(
            model_name='house',
            name='four_wheeler_parking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='two_wheeler_parking_available',
            field=models.BooleanField(default=False),
        ),
    ]
