# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreaManagers', '0001_initial'),
        ('Houses', '0016_auto_20181104_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='area_managers',
            field=models.ManyToManyField(related_name='houses', to='AreaManagers.AreaManager'),
        ),
    ]
