# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0017_house_area_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='housevisit',
            name='area_manager_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housevisit',
            name='customer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housevisit',
            name='customer_rating',
            field=models.IntegerField(default=0),
        ),
    ]
