# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0018_auto_20181114_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='Houses.SpaceSubType'),
        ),
    ]
