# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0020_auto_20190118_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='commission',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='space',
            name='rent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='space',
            name='security_deposit',
            field=models.FloatField(default=0),
        ),
    ]
