# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-28 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0021_auto_20190126_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='housevisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
