# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0024_auto_20190206_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('independent', 'Independent House'), ('villa', 'Villa')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='houseapplication',
            name='house_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('independent', 'Independent House'), ('villa', 'Villa')], max_length=25, null=True),
        ),
    ]
