# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0025_auto_20190211_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacesubtype',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=20, null=True),
        ),
    ]
