# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('Houses', '0026_spacesubtype_parent_type'),
        ('Houses', '0037_amenity_is_major')
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='managed_by',
            field=models.CharField(blank=True, choices=[(('halanx',), 'Halanx Manager'), ('self', 'Self Manager')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_included_expenses',
            field=models.ManyToManyField(blank=True, related_name='rent_excluded_houses', to='Houses.MonthlyExpenseCategory'),
        ),
    ]
