# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-13 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0026_spacesubtype_parent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='security_deposit_by_months',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_included_expenses',
            field=models.ManyToManyField(blank=True, related_name='rent_excluded_houses', to='Houses.MonthlyExpenseCategory'),
        ),
    ]
