# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0027_auto_20190615_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_managed_houses', to='Owners.Owner'),
        ),
    ]
