# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-17 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0028_auto_20190615_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Houses.House')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.Occupation')),
            ],
        ),
    ]
