# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-15 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0028_housesearchslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='housesearchslug',
            name='bhk_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='housesearchslug',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['rent_max', 'rent_max'], ['furnish_type', 'furnish_type'], ['house_type', 'house_type'], ['accomodation_allowed', 'accomodation_allowed'], ['bhk_count', 'bhk_count'], ['shared_room_bed_count', 'shared_room_bed_count'], ['accomodation_type', 'accomodation_type'], ['latitude', 'latitude'], ['longitude', 'longitude'], ['radius', 'radius']], max_length=50),
        ),
        migrations.AddField(
            model_name='housesearchslug',
            name='furnish_type',
            field=models.CharField(blank=True, choices=[('full', 'Fully furnished'), ('semi', 'Semi furnished'), ('nil', 'Unfurnished')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='housesearchslug',
            name='house_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('independent', 'Independent House'), ('villa', 'Villa')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='housesearchslug',
            name='radius',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='housesearchslug',
            name='rent_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='housesearchslug',
            name='shared_room_bed_count',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
