# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 11:19
from __future__ import unicode_literals

import Homes.Houses.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0029_occupation_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=Homes.Houses.utils.get_vendor_profile_pic_upload_path),
        ),
    ]
