# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0030_vendor_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='house',
        ),
        migrations.AddField(
            model_name='vendor',
            name='houses',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='Houses.House'),
        ),
    ]
