# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-15 08:26
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0030_auto_20190615_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housesearchslug',
            name='accomodation_allowed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family')], max_length=25),
        ),
        migrations.AlterField(
            model_name='housesearchslug',
            name='accomodation_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=25),
        ),
    ]
