# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0023_teammember_profile_pic'),
        ('Houses', '0031_auto_20190618_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Owners.Owner'),
            preserve_default=False,
        ),
    ]
