# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-27 06:14
from __future__ import unicode_literals

import Homes.Houses.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0031_auto_20190615_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to=Homes.Houses.utils.get_amenity_picture_upload_path),
        ),
    ]
