# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-20 10:12
from __future__ import unicode_literals

import Homes.Houses.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0033_remove_tenant_added_by'),
        ('Owners', '0025_auto_20190620_1542'),
        ('Houses', '0032_vendor_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Homes.Houses.utils.get_bill_picture_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField()),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Houses.Bill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tenants.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenants', models.ManyToManyField(blank=True, to='Tenants.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Houses.BillCategory'),
        ),
        migrations.AddField(
            model_name='bill',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Houses.House'),
        ),
        migrations.AddField(
            model_name='bill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Owners.Owner'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tenant_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Houses.TenantGroup'),
        ),
    ]
