# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-08 06:13
from __future__ import unicode_literals

import Homes.Houses.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0033_auto_20190702_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpensecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Homes.Houses.utils.get_monthly_expense_category_image_upload_path),
        ),
    ]
