# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-20 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0025_auto_20190620_1542'),
        ('Houses', '0033_auto_20190620_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billcategory',
            options={'verbose_name_plural': 'Bill Categories'},
        ),
        migrations.AddField(
            model_name='tenantgroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Owners.Owner'),
            preserve_default=False,
        ),
    ]
