# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0034_auto_20190620_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantgroup',
            name='tenants',
            field=models.ManyToManyField(to='Tenants.Tenant'),
        ),
    ]
