# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0035_auto_20190620_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantgroup',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
