# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-05 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0035_popularlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_params', models.TextField(blank=True, null=True)),
                ('body_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
