# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0036_sampledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='is_major',
            field=models.BooleanField(default=False),
        ),
    ]
