# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-21 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0033_remove_tenant_added_by'),
        ('Houses', '0038_auto_20190621_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Houses.House')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tenants.Tenant')),
            ],
        ),
    ]
