# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-21 11:47
from __future__ import unicode_literals

import Homes.Houses.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0039_housereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housereview',
            name='house',
        ),
        migrations.RemoveField(
            model_name='housereview',
            name='tenant',
        ),
        migrations.AddField(
            model_name='billcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Homes.Houses.utils.get_category_image_upload_path),
        ),
        migrations.DeleteModel(
            name='HouseReview',
        ),
    ]
