# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-22 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0040_auto_20190621_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsplit',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='Houses.Bill'),
        ),
        migrations.AlterField(
            model_name='billsplit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='Tenants.Tenant'),
        ),
    ]
