# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-14 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0041_auto_20190622_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rent_included_expenses',
            field=models.ManyToManyField(blank=True, related_name='rent_included_houses', to='Houses.MonthlyExpenseCategory'),
        ),
    ]
