# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0043_auto_20190814_2232'),
        ('Owners', '0027_tenantgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantgroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='tenants',
        ),
        migrations.AlterField(
            model_name='bill',
            name='tenant_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Owners.TenantGroup'),
        ),
        migrations.DeleteModel(
            name='TenantGroup',
        ),
    ]
