# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 13:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNo', models.CharField(blank=True, max_length=30, unique=True)),
                ('GcmId', models.CharField(blank=True, max_length=500, null=True)),
                ('MyReferralCode', models.CharField(blank=True, max_length=50, null=True)),
                ('ReferredBy', models.BigIntegerField(blank=True, null=True)),
                ('ReferralCode', models.CharField(blank=True, max_length=50, null=True)),
                ('PromotionalBalance', models.FloatField(blank=True, default=0.0)),
                ('AccessToken', models.CharField(blank=True, max_length=300, null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('LastItem', models.IntegerField(blank=True, null=True)),
                ('SubscriptionTotal', models.FloatField(blank=True, default=0.0)),
                ('SubscriptionStatus', models.BooleanField(default=True)),
                ('AvgRating', models.FloatField(blank=True, default=3.0)),
                ('n', models.IntegerField(blank=True, default=0)),
                ('AccountBalance', models.FloatField(blank=True, default=0.0, null=True)),
                ('FavoriteItems', models.ManyToManyField(blank=True, to='Products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
