# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PhoneNo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
