# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0003_auto_20170901_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
