# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0004_auto_20170903_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='PhoneNo',
            field=models.CharField(default=b'123', max_length=30),
        ),
        migrations.AlterField(
            model_name='otp',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
