# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0005_auto_20170907_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='PhoneNo',
            field=models.CharField(default='123', max_length=30),
        ),
    ]
