# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Carts', '0003_auto_20171009_1728'),
        ('UserBase', '0006_auto_20170918_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='GroupCart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='Carts.Cart'),
        ),
    ]
