# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0009_auto_20171104_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='FavoriteItems',
            field=models.ManyToManyField(blank=True, null=True, to='Products.Product'),
        ),
    ]
