# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0010_auto_20171106_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='FavoriteItems',
            field=models.ManyToManyField(blank=True, to='Products.Product'),
        ),
    ]
