# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0011_auto_20171108_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_registered',
            field=models.BooleanField(default=True),
        ),
    ]
