# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0013_auto_20171118_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
