# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0015_customer_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ProfilePic',
            field=models.TextField(blank=True, help_text='In Base64', null=True),
        ),
    ]
