# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0016_auto_20171123_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PhoneNo',
            field=models.CharField(max_length=30, unique=True, validators=[
                django.core.validators.RegexValidator('^[+]*\\d{10,}$',
                                                      message='Phone Number should be contain atleast 10 numeric numbers')]),
        ),
    ]
