# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models

import UserBase.models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0017_auto_20171124_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to=UserBase.models.get_picture_upload_path),
        ),
    ]
