# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0018_auto_20171126_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='UserInterests',
            field=models.ManyToManyField(blank=True, null=True, to='UserBase.UserInterest'),
        ),
    ]
