# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0019_auto_20171204_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='UserInterests',
            field=models.ManyToManyField(blank=True, to='UserBase.UserInterest'),
        ),
    ]
