# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0020_auto_20171204_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='subInterests',
            field=models.ManyToManyField(blank=True, related_name='_userinterest_subInterests_+',
                                         to='UserBase.UserInterest'),
        ),
    ]
