# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 09:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0021_userinterest_subinterests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='priority',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1),
                                                                     django.core.validators.MaxValueValidator(10)]),
        ),
    ]
