# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0022_userinterest_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('from_year', models.CharField(blank=True, max_length=4, null=True)),
                ('to_year', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('from_year', models.CharField(blank=True, max_length=4, null=True)),
                ('to_year', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='RelationshipStatus',
            field=models.CharField(blank=True,
                                   choices=[('Single', 'Single'), ('In a relationship', 'In a relationship'),
                                            ('Engaged', 'Engaged'), ('Married', 'Married'), ('Divorced', 'Divorced'),
                                            ('Widowed', 'Widowed'), ('Separated', 'Separated'),
                                            ("It's complicated", "It's complicated")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Academics',
            field=models.ManyToManyField(blank=True, to='UserBase.Education'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Occupation',
            field=models.ManyToManyField(blank=True, to='UserBase.Work'),
        ),
    ]
