# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 08:51
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0023_auto_20171221_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Academics',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Occupation',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserBase.Customer'),
        ),
        migrations.AddField(
            model_name='work',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserBase.Customer'),
        ),
        migrations.AlterField(
            model_name='education',
            name='from_year',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1000),
                                                          django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_year',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1000),
                                                          django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='from_year',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1000),
                                                          django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='to_year',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1000),
                                                          django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
