# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0025_auto_20171221_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_completion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='receive_notification',
            field=models.BooleanField(default=True),
        ),
    ]
