# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0026_auto_20171221_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='VerifiedEmail',
            field=models.BooleanField(default=False),
        ),
    ]
