# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0027_customer_verifiedemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='FavoriteItems',
        ),
    ]
