# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 17:11
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0029_customer_favoriteitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=30, unique=True, validators=[
                    django.core.validators.RegexValidator('^[+]*\\d{10,}$',
                                                          message='Phone Number should be contain atleast 10 numeric numbers')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserBase.Customer')),
            ],
        ),
    ]
