# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0031_auto_20180125_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=30),
        ),
    ]
