# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0032_auto_20180126_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
