# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0038_auto_20180310_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
