# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0039_picture_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ProfilePic',
        ),
    ]
