# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0040_remove_customer_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
