# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 19:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0043_auto_20180321_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserBase.Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='Places.Region'),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education',
                                    to='UserBase.Customer'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures',
                                    to='UserBase.Customer'),
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work',
                                    to='UserBase.Customer'),
        ),
    ]
