# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 13:52
from __future__ import unicode_literals

from django.db import migrations, models

import UserBase.models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0044_auto_20180322_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=UserBase.models.get_thumbnail_upload_path),
        ),
    ]
