# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0045_picture_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='LastItem',
        ),
    ]
