# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Places', '0024_remove_picture_checkin'),
        ('UserBase', '0046_remove_customer_lastitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='FavoritePlaces',
            field=models.ManyToManyField(blank=True, to='Places.Place'),
        ),
        migrations.AddField(
            model_name='customer',
            name='follows',
            field=models.ManyToManyField(related_name='_customer_follows_+', to='UserBase.Customer'),
        ),
    ]
