# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0051_auto_20180430_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='my_referral_code',
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
