# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0052_auto_20180513_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
