# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-08 12:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0053_auto_20180513_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=30, unique=True, validators=[
                django.core.validators.RegexValidator('^[+]*\\d{10,}$',
                                                      message='Phone Number should be contain at least 10 numeric numbers')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic_thumbnail_url',
            field=models.CharField(blank=True,
                                   default='https://d28fujbigzf56k.cloudfront.net/static/img/nopic_small.jpg',
                                   max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic_url',
            field=models.CharField(blank=True, default='https://d28fujbigzf56k.cloudfront.net/static/img/nopic.jpg',
                                   max_length=500, null=True),
        ),
    ]
