# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0054_auto_20180708_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='spamreport',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spam_reports', to='UserBase.Customer'),
        ),
    ]
