# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0055_auto_20180803_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='UserBase.Customer'),
        ),
    ]
