# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0056_auto_20180804_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='customer',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='UserBase.Customer'),
        ),
    ]
