# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0057_auto_20180804_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='UserBase.Customer'),
        ),
    ]
