# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-19 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0058_auto_20180810_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='hcash',
            field=models.FloatField(default=0.0),
        ),
    ]
