# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0005_campaign_code'),
        ('UserBase', '0060_auto_20190205_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Promotions.Campaign'),
        ),
    ]
