# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 09:55
from __future__ import unicode_literals

import Homes.Owners.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0002_ownerpayment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('Sample', 'Sample')], max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('payload', jsonfield.fields.JSONField(blank=True, null=True)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerNotificationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Homes.Owners.utils.get_owner_notification_image_upload_path)),
                ('category', models.CharField(blank=True, choices=[('Sample', 'Sample')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerdocument',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_no',
            field=models.CharField(default=False, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[+]*\\d{10,}$', message='Phone Number should be contain at least 10 numeric numbers')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownernotification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Owners.Owner'),
        ),
    ]
