# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0007_auto_20180705_2252'),
        ('Owners', '0003_auto_20180806_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpayment',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaction.CustomerTransaction'),
        ),
        migrations.AlterField(
            model_name='ownernotification',
            name='category',
            field=models.CharField(blank=True, choices=[('RentDeposit', 'RentDeposit'), ('SuccessfulWithdrawal', 'SuccessfulWithdrawal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ownernotificationimage',
            name='category',
            field=models.CharField(blank=True, choices=[('RentDeposit', 'RentDeposit'), ('SuccessfulWithdrawal', 'SuccessfulWithdrawal')], max_length=50, null=True),
        ),
    ]
