# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-16 08:26
from __future__ import unicode_literals

import Homes.Owners.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0005_auto_20180812_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdocument',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=Homes.Owners.utils.get_owner_document_thumbnail_upload_path),
        ),
    ]
