# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0010_auto_20180822_2258'),
        ('Owners', '0006_ownerdocument_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_referrals', to='Tenants.Tenant'),
        ),
    ]
