# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0009_houseownertransaction_storetransaction_tenanttransaction'),
        ('Owners', '0008_remove_ownerpayment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpayment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaction.HouseOwnerTransaction'),
        ),
    ]
