# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0011_owner_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
