# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-21 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0013_auto_20181021_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='correspondant_relation',
            field=models.CharField(blank=True, choices=[('S/o', 'S/o'), ('D/o', 'D/o'), ('W/o', 'W/o')], max_length=10, null=True),
        ),
    ]
