# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0014_auto_20181021_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='gstin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
