# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0015_owner_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMonthlyRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rent', models.FloatField()),
                ('commission', models.FloatField()),
                ('gst', models.FloatField()),
                ('total', models.FloatField()),
                ('credited', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_rents', to='Owners.OwnerWallet')),
            ],
        ),
    ]
