# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0016_ownermonthlyrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpayment',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
