# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0017_auto_20181220_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMonthlyEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rent', models.FloatField(default=0)),
                ('commission', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('credited', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_earnings', to='Owners.Owner')),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_earning', to='Owners.OwnerPayment')),
            ],
        ),
        migrations.RemoveField(
            model_name='ownermonthlyrent',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='OwnerMonthlyRent',
        ),
    ]
