# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0018_auto_20190308_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='Owners.Owner')),
            ],
        ),
        migrations.AlterField(
            model_name='ownerpayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_payments', to='Transaction.HouseOwnerTransaction'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='Owners.OwnerPayment'),
        ),
    ]
