# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-17 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('Owners', '0019_auto_20190315_1610'),
        ('Owners', '0025_auto_20190809_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
