# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-17 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0020_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='owner',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.PROTECT, to='Owners.Owner'),
            preserve_default=False,
        ),
    ]
