# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 11:09
from __future__ import unicode_literals

import Homes.Owners.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0022_teammember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=Homes.Owners.utils.get_owner_team_members_profile_pic_upload_path),
        ),
    ]
