# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-30 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0023_ownerlisting_furnish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerlisting',
            name='house_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ownerlisting',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerlisting',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
