# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0032_vendor_owner'),
        ('Owners', '0023_teammember_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='houses',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='Houses.House'),
        ),
    ]
