# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0033_remove_tenant_added_by'),
        ('Owners', '0026_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Owners.Owner')),
                ('tenants', models.ManyToManyField(to='Tenants.Tenant')),
            ],
        ),
    ]
