# Generated by Django 2.0 on 2018-07-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
