# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-02 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_customer_profile_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
