# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 14:08
from __future__ import unicode_literals

import Common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Common', '0003_auto_20180802_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=Common.utils.get_payment_category_icon_upload_path)),
            ],
        ),
    ]
