# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 14:03
from __future__ import unicode_literals

import Homes.AreaManagers.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('area', models.CharField(blank=True, max_length=300, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, help_text='In km.', null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=Homes.AreaManagers.utils.get_area_manager_profile_pic_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
