# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0002_auto_20180804_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdocument',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
