# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0007_auto_20180705_2252'),
        ('Tenants', '0003_tenantdocument_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayment',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaction.CustomerTransaction'),
        ),
    ]
