# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0009_remove_flat_bhk_count'),
        ('Tenants', '0005_auto_20180812_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='favorite_houses',
            field=models.ManyToManyField(blank=True, to='Houses.House'),
        ),
    ]
