# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0007_auto_20180814_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='referral_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
