# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-16 08:26
from __future__ import unicode_literals

import Homes.Tenants.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0008_auto_20180814_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdocument',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=Homes.Tenants.utils.get_tenant_document_thumbnail_upload_path),
        ),
    ]
