# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0009_tenantdocument_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='referral_code',
            new_name='tenant_referral_code',
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_referral_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_referrals', to='Tenants.Tenant'),
        ),
    ]
