# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0010_auto_20180822_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantpayment',
            name='transaction',
        ),
    ]
