# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0012_tenantpayment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpayment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaction.CustomerTransaction'),
        ),
    ]
