# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0014_auto_20180830_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='job_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
