# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0015_tenant_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_payments', to='Transaction.CustomerTransaction'),
        ),
    ]
