# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0016_auto_20181105_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayment',
            name='apply_cashback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
