# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0017_auto_20181214_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayment',
            name='original_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
