# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0018_tenantpayment_original_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpayment',
            name='original_amount',
            field=models.FloatField(null=True),
        ),
    ]
