# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-17 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0021_auto_20181220_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('preferred_location', models.TextField(blank=True, null=True)),
                ('expected_rent', models.IntegerField(blank=True, null=True)),
                ('expected_movein_date', models.DateTimeField(blank=True, null=True)),
                ('accomodation_for', models.CharField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family')], max_length=50, null=True)),
                ('accomodation_type', models.CharField(blank=True, choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='Tenants.Tenant')),
            ],
        ),
    ]
