# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0022_tenantrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequirement',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
