# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0023_tenantrequirement_affiliate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
