# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-17 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0022_teammember_email'),
        # ('Tenants', '0024_tenant_affiliate_code'),
        ('Tenants', '0029_auto_20190809_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='added_by',
            field=models.ManyToManyField(blank=True, to='Owners.Owner'),
        ),
    ]
