# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0022_auto_20190408_2035'),
        ('Tenants', '0025_tenant_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLateCheckin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('current_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bookings.Booking')),
            ],
        ),
    ]
