# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-02 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0025_auto_20190705_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMoveOutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moveout_requests', to='Tenants.Tenant')),
            ],
        ),
    ]
