# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0026_tenantlatecheckin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantlatecheckin',
            old_name='datetime',
            new_name='expected_checkin',
        ),
    ]
