# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0028_auto_20190618_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('breakfast', 'Breakast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('accepted_by', models.ManyToManyField(blank=True, to='Tenants.Tenant')),
            ],
        ),
    ]
