# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0029_tenantmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmeal',
            name='meal',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
