# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-17 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0033_remove_tenant_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcompanyaddressdetail',
            name='zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantpermanentaddressdetail',
            name='zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
