# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bookings', '0002_booking_space'),
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Tenants.Tenant'),
        ),
    ]
