# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_monthlyrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrent',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_rent', to='Tenants.TenantPayment'),
        ),
    ]
