# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0008_auto_20181022_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfacility',
            name='remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
