# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_bookingfacility_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='move_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='moved_out',
            field=models.BooleanField(default=False),
        ),
    ]
