# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0010_auto_20181105_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingfacility',
            options={'verbose_name_plural': 'Booking Facilities'},
        ),
        migrations.AddField(
            model_name='booking',
            name='move_in_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='move_out_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
