# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-10 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_auto_20181108_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='move_out_date',
            new_name='license_end_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='area_manager_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingfacility',
            name='status',
            field=models.CharField(choices=[('Allocated', 'Allocated'), ('Returned', 'Returned'), ('Lost', 'Lost'), ('Damaged', 'Damaged')], default='Allocated', max_length=50),
        ),
    ]
