# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0012_auto_20181110_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrent',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
