# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0014_auto_20190211_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancebooking',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
