# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0003_auto_20190212_1256'),
        ('Bookings', '0015_advancebooking_preferred_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancebooking',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_bookings', to='Promotions.PromoCode'),
        ),
    ]
