# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0018_auto_20190308_2007'),
        ('Bookings', '0016_advancebooking_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrent',
            name='fine',
        ),
        migrations.AddField(
            model_name='monthlyrent',
            name='owner_monthly_earning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_rents', to='Owners.OwnerMonthlyEarning'),
        ),
    ]
