# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0017_auto_20190308_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrent',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
