# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0018_monthlyrent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrent',
            name='owner_monthly_earning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_rents', to='Owners.OwnerMonthlyEarning'),
        ),
    ]
