# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-08 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0021_auto_20190327_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existingtenantonboarding',
            name='last_monthly_rent_paid_on',
        ),
        migrations.RemoveField(
            model_name='existingtenantonboarding',
            name='last_monthly_rent_paid_to_owner',
        ),
        migrations.RemoveField(
            model_name='monthlyrent',
            name='cancelled',
        ),
    ]
