# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-13 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0022_auto_20190408_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='security_deposit_by_months',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
