# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-13 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Promotions', '0008_auto_20190613_1649'),
        ('Bookings', '0023_booking_security_deposit_by_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Promotions.PromoCode'),
        ),
    ]
