# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0025_auto_20190711_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfacility',
            name='quantity_acknowledged',
            field=models.IntegerField(default=0),
        ),
    ]
