# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-17 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0029_auto_20190809_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agreement_signed',
            field=models.BooleanField(default=False),
        ),
    ]
