# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0030_booking_agreement_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agreement_verification_error_notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='agreement_verification_status',
            field=models.CharField(choices=[('unsigned', 'Signature not uploaded'), ('verified', 'Verification Complete'), ('ongoing', 'Verification Ongoing'), ('error', 'Error in Verification')], default='unsigned', max_length=30),
        ),
    ]
