# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 17:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancelRefundCaptureRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=100)),
                ('mihpayid', models.CharField(max_length=100)),
                ('bank_ref_num', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('error_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_gateway_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_date_time', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('mihpayid', models.CharField(blank=True, max_length=100, null=True)),
                ('bankcode', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('additional_charges', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('txn_status_on_payu', models.CharField(blank=True, max_length=20, null=True)),
                ('hash_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        # migrations.AddField(
        #     model_name='cancelrefundcapturerequests',
        #     name='transaction',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.CustomerTransaction'),
        # ),
    ]
