# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 13:01
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='cancelrefundcapturerequests',
        #     name='transaction',
        # ),
        migrations.RemoveField(
            model_name='transaction',
            name='additional_charges',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank_ref_num',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bankcode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='hash_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mihpayid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='txn_status_on_payu',
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True,
                                       default=datetime.datetime(2018, 4, 23, 13, 1, 58, 191340, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CancelRefundCaptureRequests',
        ),
    ]
