# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Transaction', '0003_auto_20180423_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_gateway_type',
            new_name='payment_gateway',
        ),
    ]
