# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 14:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserBase', '0053_auto_20180513_2252'),
        ('Transaction', '0004_auto_20180516_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserBase.Customer'),
        ),
    ]
