# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Transaction', '0005_transaction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='platform',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('android', 'android')], max_length=20,
                                   null=True),
        ),
    ]
