# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0007_auto_20180705_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='CustomerTransaction',
        ),
    ]
