# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBase', '0037_remove_storepayment_store'),
        ('Owners', '0008_remove_ownerpayment_transaction'),
        ('Tenants', '0011_remove_tenantpayment_transaction'),
        ('Transaction', '0008_auto_20180823_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOwnerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_gateway', models.CharField(blank=True, choices=[('payu', 'payu'), ('paytm', 'paytm')], max_length=20, null=True)),
                ('platform', models.CharField(blank=True, choices=[('web', 'web'), ('android', 'android')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Owners.Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_gateway', models.CharField(blank=True, choices=[('payu', 'payu'), ('paytm', 'paytm')], max_length=20, null=True)),
                ('platform', models.CharField(blank=True, choices=[('web', 'web'), ('android', 'android')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StoreBase.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_gateway', models.CharField(blank=True, choices=[('payu', 'payu'), ('paytm', 'paytm')], max_length=20, null=True)),
                ('platform', models.CharField(blank=True, choices=[('web', 'web'), ('android', 'android')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tenants.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
