# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0009_houseownertransaction_storetransaction_tenanttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenanttransaction',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='TenantTransaction',
        ),
    ]
