# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0010_auto_20180824_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='houseownertransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
