# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0011_auto_20180824_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransaction',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('PayU', 'PayU'), ('Paytm', 'Paytm'), ('Fund Transfer', 'Fund Transfer'), ('Cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='houseownertransaction',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('PayU', 'PayU'), ('Paytm', 'Paytm'), ('Fund Transfer', 'Fund Transfer'), ('Cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='houseownertransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('PayU', 'PayU'), ('Paytm', 'Paytm'), ('Fund Transfer', 'Fund Transfer'), ('Cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
