# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0015_auto_20181113_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='deposit_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='deposit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='deposited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseownertransaction',
            name='deposit_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseownertransaction',
            name='deposit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseownertransaction',
            name='deposited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='deposit_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='deposit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='deposited',
            field=models.BooleanField(default=False),
        ),
    ]
