# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0017_auto_20181114_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='houseownertransaction',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
