# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-11 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0019_auto_20190126_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransaction',
            name='platform',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('android', 'android'), ('ios', 'ios')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='houseownertransaction',
            name='platform',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('android', 'android'), ('ios', 'ios')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='platform',
            field=models.CharField(blank=True, choices=[('web', 'web'), ('android', 'android'), ('ios', 'ios')], max_length=20, null=True),
        ),
    ]
