# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-29 17:58
from __future__ import unicode_literals

import Transaction.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0020_auto_20190211_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='deposit_reference_image',
            field=models.ImageField(blank=True, null=True, upload_to=Transaction.utils.get_deposit_reference_image_upload_path),
        ),
        migrations.AddField(
            model_name='houseownertransaction',
            name='deposit_reference_image',
            field=models.ImageField(blank=True, null=True, upload_to=Transaction.utils.get_deposit_reference_image_upload_path),
        ),
        migrations.AddField(
            model_name='storetransaction',
            name='deposit_reference_image',
            field=models.ImageField(blank=True, null=True, upload_to=Transaction.utils.get_deposit_reference_image_upload_path),
        ),
    ]
