# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0022_auto_20190702_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransaction',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('PayU', 'PayU'), ('Paytm', 'Paytm'), ('NEFT/IMPS', 'NEFT/IMPS'), ('Cash', 'Cash'), ('Razorpay', 'Razorpay'), ('TotalHcash', 'TotalHcash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='houseownertransaction',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('PayU', 'PayU'), ('Paytm', 'Paytm'), ('NEFT/IMPS', 'NEFT/IMPS'), ('Cash', 'Cash'), ('Razorpay', 'Razorpay'), ('TotalHcash', 'TotalHcash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storetransaction',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('PayU', 'PayU'), ('Paytm', 'Paytm'), ('NEFT/IMPS', 'NEFT/IMPS'), ('Cash', 'Cash'), ('Razorpay', 'Razorpay'), ('TotalHcash', 'TotalHcash')], max_length=20, null=True),
        ),
    ]
