# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 17:14
from __future__ import unicode_literals

import Homes.HomeServices.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bookings', '0005_auto_20180808_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Homes.HomeServices.utils.get_service_category_picture_upload_path)),
                ('is_parent', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='HomeServices.ServiceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_resolved', 'Not resolved'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='not_resolved', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='Bookings.Booking')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='HomeServices.ServiceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='SupportStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Homes.HomeServices.utils.get_support_staff_member_picture_upload_path)),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='support_staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='HomeServices.SupportStaffMember'),
        ),
    ]
