# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0002_auto_20180808_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Not Resolved', 'Not Resolved'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Not Resolved', max_length=30),
        ),
    ]
