# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0003_auto_20180814_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='HomeServices.ServiceRequest')),
            ],
        ),
    ]
