# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-08 05:43
from __future__ import unicode_literals

import Homes.HomeServices.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0004_servicerequestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestimage',
            name='image',
            field=models.ImageField(upload_to=Homes.HomeServices.utils.get_service_request_picture_upload_path),
        ),
    ]
