# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-16 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0006_supportstaffmembermajorservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supportstaffmembermajorservice',
            unique_together=set([('staff_member', 'category')]),
        ),
    ]
