# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0009_supportstaffmemberworkaddressdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
