# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Notifications', '0004_auto_20171226_1819'),
        ('Notifications', '0004_auto_20171226_1822'),
    ]

    operations = [
    ]
