# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models

from Notifications.utils import get_notification_image_upload_path


class Migration(migrations.Migration):
    dependencies = [
        ('Notifications', '0005_merge_20171226_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True,
                                            upload_to=get_notification_image_upload_path)),
                ('category', models.CharField(blank=True, choices=[('InsufficientBalance1', 'InsufficientBalance1'),
                                                                   ('InsufficientBalance2', 'InsufficientBalance2'),
                                                                   ('BatchAccepted', 'BatchAccepted'),
                                                                   ('BatchDelivered', 'BatchDelivered'),
                                                                   ('CashBack', 'CashBack'),
                                                                   ('TitleAssigned', 'TitleAssigned')], max_length=50,
                                              null=True)),
            ],
        ),
    ]
