# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Notifications', '0008_auto_20180202_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('InsufficientBalance1', 'InsufficientBalance1'),
                                                        ('InsufficientBalance2', 'InsufficientBalance2'),
                                                        ('BatchAccepted', 'BatchAccepted'),
                                                        ('BatchDelivered', 'BatchDelivered'),
                                                        ('OrderDelivered', 'OrderDelivered'), ('CashBack', 'CashBack'),
                                                        ('TitleAssigned', 'TitleAssigned'), ('Alert', 'Alert'),
                                                        ('Announcement', 'Announcement'), ('NewMessage', 'NewMessage')],
                                   max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificationimage',
            name='category',
            field=models.CharField(blank=True, choices=[('InsufficientBalance1', 'InsufficientBalance1'),
                                                        ('InsufficientBalance2', 'InsufficientBalance2'),
                                                        ('BatchAccepted', 'BatchAccepted'),
                                                        ('BatchDelivered', 'BatchDelivered'),
                                                        ('OrderDelivered', 'OrderDelivered'), ('CashBack', 'CashBack'),
                                                        ('TitleAssigned', 'TitleAssigned'), ('Alert', 'Alert'),
                                                        ('Announcement', 'Announcement'), ('NewMessage', 'NewMessage')],
                                   max_length=50, null=True),
        ),
    ]
