# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Notifications', '0009_auto_20180315_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
