# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0012_auto_20180808_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
