# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0017_auto_20190213_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('InsufficientBalance1', 'InsufficientBalance1'), ('InsufficientBalance2', 'InsufficientBalance2'), ('BatchAccepted', 'BatchAccepted'), ('BatchDelivered', 'BatchDelivered'), ('OrderDelivered', 'OrderDelivered'), ('CashBack', 'CashBack'), ('PromoCodeCashBack', 'PromoCodeCashBack'), ('TitleAssigned', 'TitleAssigned'), ('Alert', 'Alert'), ('Announcement', 'Announcement'), ('NewMessage', 'NewMessage'), ('PlaceVisit', 'PlaceVisit'), ('DueTenantPayment', 'DueTenantPayment'), ('SuccessfulTenantPayment', 'SuccessfulTenantPayment'), ('PostLiked', 'PostLiked')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificationimage',
            name='category',
            field=models.CharField(blank=True, choices=[('InsufficientBalance1', 'InsufficientBalance1'), ('InsufficientBalance2', 'InsufficientBalance2'), ('BatchAccepted', 'BatchAccepted'), ('BatchDelivered', 'BatchDelivered'), ('OrderDelivered', 'OrderDelivered'), ('CashBack', 'CashBack'), ('PromoCodeCashBack', 'PromoCodeCashBack'), ('TitleAssigned', 'TitleAssigned'), ('Alert', 'Alert'), ('Announcement', 'Announcement'), ('NewMessage', 'NewMessage'), ('PlaceVisit', 'PlaceVisit'), ('DueTenantPayment', 'DueTenantPayment'), ('SuccessfulTenantPayment', 'SuccessfulTenantPayment'), ('PostLiked', 'PostLiked')], max_length=50, null=True),
        ),
    ]
