# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-25 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0018_auto_20190624_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('InsufficientBalance1', 'InsufficientBalance1'), ('InsufficientBalance2', 'InsufficientBalance2'), ('BatchAccepted', 'BatchAccepted'), ('BatchDelivered', 'BatchDelivered'), ('OrderDelivered', 'OrderDelivered'), ('CashBack', 'CashBack'), ('PromoCodeCashBack', 'PromoCodeCashBack'), ('TitleAssigned', 'TitleAssigned'), ('Alert', 'Alert'), ('Announcement', 'Announcement'), ('NewMessage', 'NewMessage'), ('PlaceVisit', 'PlaceVisit'), ('DueTenantPayment', 'DueTenantPayment'), ('SuccessfulTenantPayment', 'SuccessfulTenantPayment'), ('PostLiked', 'PostLiked'), ('CommentLiked', 'CommentLiked'), ('NewComment', 'NewComment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificationimage',
            name='category',
            field=models.CharField(blank=True, choices=[('InsufficientBalance1', 'InsufficientBalance1'), ('InsufficientBalance2', 'InsufficientBalance2'), ('BatchAccepted', 'BatchAccepted'), ('BatchDelivered', 'BatchDelivered'), ('OrderDelivered', 'OrderDelivered'), ('CashBack', 'CashBack'), ('PromoCodeCashBack', 'PromoCodeCashBack'), ('TitleAssigned', 'TitleAssigned'), ('Alert', 'Alert'), ('Announcement', 'Announcement'), ('NewMessage', 'NewMessage'), ('PlaceVisit', 'PlaceVisit'), ('DueTenantPayment', 'DueTenantPayment'), ('SuccessfulTenantPayment', 'SuccessfulTenantPayment'), ('PostLiked', 'PostLiked'), ('CommentLiked', 'CommentLiked'), ('NewComment', 'NewComment')], max_length=50, null=True),
        ),
    ]
